web_dev:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres_dev:postgres
  volumes:
    - ./web:/usr/src/app
    - ./web/static:/usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

nginx_dev:
  restart: always
  build: ./nginx_dev/
  ports:
    - "8080:8080"
  volumes:
    - ./nginx:/www/static
  volumes_from:
    - web_dev
  links:
    - web_dev:web

postgres_dev:
  restart: always
  image: postgres:latest
  ports:
    - "5432"
  volumes:
    - acc_pgdata_dev:/var/lib/postgresql/data/

